### ISSUE TITLE
List::Compare not loaded in Map/Metro/Graph/LineStation.pm

### ISSUE THREAD

**Issue by eserte** [Csson/p5-Map-Metro-Plugin-Map-Stockholm#1]
Sample fail report: http://www.cpantesters.org/cpan/report/a64993f6-e6d5-11e5-9e62-aeec73a6cd38
It can be reproduced on a fresh system where some hook plugins (Map::Metro::Plugin::Hook::Helsinki::Swedish?) are not installed.

**Comment by eserte** [comment]
As I see the problem also in other Map::Metro::Plugin::Map::\* modules, it's probably a global Map::Metro problem.

**Comment by Csson** [comment]
Should be fixed in Map::Metro 0.2403.

Thanks!
